// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-XIVIdd_ByFtkKBhy3D7O4rj1CLHbzY',
    appId: '1:283905417668:web:939179be402379878e0491',
    messagingSenderId: '283905417668',
    projectId: 'nader_driver-b9589',
    authDomain: 'nader_driver-b9589.firebaseapp.com',
    storageBucket: 'nader_driver-b9589.firebasestorage.app',
    measurementId: 'G-Y93PHBNFJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfy3mDMpZ0IdgzKPfd0HCZBadRh88jKyE',
    appId: '1:399511821795:android:19b0438c054e596d3d14d6',
    messagingSenderId: '399511821795',
    projectId: 'brothers-taxi',
    storageBucket: 'brothers-taxi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdC6pYKbRzJMwjZTBYqERi2vsdsghEOM',
    appId: '1:399511821795:ios:deece7a79a8446213d14d6',
    messagingSenderId: '399511821795',
    projectId: 'brothers-taxi',
    storageBucket: 'brothers-taxi.firebasestorage.app',
    iosBundleId: 'com.brothertaxi.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQokP98SSvqCGAo_e15ppfvWQ2QhByqs',
    appId: '1:283905417668:ios:d1ed7b8ed2c66bfd8e0491',
    messagingSenderId: '283905417668',
    projectId: 'nader_driver-b9589',
    storageBucket: 'nader_driver-b9589.firebasestorage.app',
    iosBundleId: 'com.example.nader_driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6-XIVIdd_ByFtkKBhy3D7O4rj1CLHbzY',
    appId: '1:283905417668:web:74694e0b3aa43cc18e0491',
    messagingSenderId: '283905417668',
    projectId: 'nader_driver-b9589',
    authDomain: 'nader_driver-b9589.firebaseapp.com',
    storageBucket: 'nader_driver-b9589.firebasestorage.app',
    measurementId: 'G-6ZWMKDLSLD',
  );
}